config/routes.rb
Rails.application.routes.draw do
  resources :analytics, only: :index

  ActiveAdmin.routes(self)
  filter :locale

  root 'main#index'
  mount ApiFlashcards::Engine => "/api_flashcards"

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login' => 'user_sessions#new', as: :login

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout' => 'user_sessions#destroy', as: :logout

    resources :cards do
      collection do
        get 'flickr_photos_search'
      end
    end

    resources :fillings do
      collection do
        get 'result'
      end
    end

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'

    get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
    put 'profile/:id' => 'profile#update', as: :profile
  end
end

app/views/layouts/header/_login_navbar_links.html.erb
<%= link_to t(:user_profile_label), edit_profile_path(current_user),
            class: 'navbar-link' %> |
<%= link_to t(:delete_user_label), user_path(current_user),
            method: :delete, class: 'navbar-link',
            data: { confirm: t(:delete_user_label) } %> |
<%= link_to t(:log_out_label), :logout, method: :post,
            class: 'navbar-link' %>

app/views/layouts/header/_logout_navbar_links.html.erb
<%= link_to t(:sing_up_label), new_user_path,
            class: 'navbar-link' %> |
<%= link_to t(:log_in_with_github_label),
            auth_at_provider_path(provider: :github),
            class: 'navbar-link'%> |
<%= link_to t(:log_in_label), :login, class: 'navbar-link' %> |
<% I18n.available_locales.each do |locale| %>
  <%=link_to locale, root_path(user_locale: locale),
             class: 'navbar-link'%>
<% end %>

app/views/layouts/header/_navbar_menu_links.html.erb
<li><%= link_to t(:all_blocks_label), blocks_path %></li>
<li><%= link_to t(:add_block_label), new_block_path %></li>
<li><%= link_to t(:all_cards_label), cards_path %></li>
<li><%= link_to t(:add_card_label), new_card_path %></li>
<li><%= link_to t(:add_filling_label), new_filling_path %></li>