config/routes.rb
Rails.application.routes.draw do
  resources :analytics, only: :index

  ActiveAdmin.routes(self)
  filter :locale

  root 'main#index'
  mount ApiFlashcards::Engine => "/api_flashcards"

  scope module: 'home' do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get 'login' => 'user_sessions#new', as: :login

    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope module: 'dashboard' do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post 'logout' => 'user_sessions#destroy', as: :logout

    resources :cards do
      collection do
        get 'flickr_photos_search'
      end
    end

    resources :fillings do
      collection do
        get 'result'
      end
    end

    resources :blocks do
      member do
        put 'set_as_current'
        put 'reset_as_current'
      end
    end

    put 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'

    get 'profile/:id/edit' => 'profile#edit', as: :edit_profile
    put 'profile/:id' => 'profile#update', as: :profile
  end
end

app/models/filling.rb
class Filling < ApplicationRecord
  include Userable
  
  belongs_to :block
  validates :block_id, presence: { message: 'Выберите колоду из выпадающего списка.' }
  validates :original_selector, :translated_selector, :url, presence: true
  validates_format_of :url, :with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login, :track_action
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  protected

  def track_action
    if current_user
      ahoy.authenticate(current_user)
      ahoy.track "Viewed #{controller_name}##{action_name}", user_id: current_user.id
    end
  end

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = t(:not_found_alert)
    redirect_to root_path
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:destroy, :edit, :update, :set_as_current, :reset_as_current]

  def index
    @blocks = current_user.blocks.all.order('title')
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      render :new
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      render :edit
    end
  end

  def destroy
    @block.destroy
    redirect_to blocks_url, notice: 'Block was successfully destroyed.'
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      ahoy.track "card:added", card_id: @card.id
      redirect_to cards_path
    else
      render :new
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_url, notice: 'Card was successfully destroyed.'
  end

  def flickr_photos_search
    @list_images = Flickr.new(params[:query]).flickr_search

    if @list_image.present?
      respond_to do |format|
        format.js {render layout: false}
      end
    end
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id,
                                 :remote_image_url)
  end
end

app/controllers/dashboard/fillings_controller.rb
class Dashboard::FillingsController < Dashboard::BaseController
  def show
    filling_result = FillingResult.where(job_id: params[:id])
    @cards         = Card.where(id: filling_result)
  end

  def new
    @filling = current_user.fillings.build
  end

  def create
    @filling = current_user.fillings.build(filling_params)
    respond_to do |format| 
      if @filling.save 
        RemoteFillingJob.perform_later @filling.id, current_user.id
        format.html { redirect_to @filling, notice: 'Filling was successfully created.' }    
      else 
        format.html { render :new } 
      end 
    end 
  end

  private

  def filling_params
    params.require(:filling).permit(:original_selector, :translated_selector, 
                                    :block_id, :user_id, :url)
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::BaseController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path, notice: 'Профиль пользователя успешно обновлен.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :locale)
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController
  include CreatingCard

  def index
    create_card(params)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def review_card
    @card = current_user.cards.find(params[:card_id])
    check_result(@card)
    ahoy.track "card:reviewed", card_id: @card.id
  end

  private

  def trainer_params
    params.permit(:user_translation)
  end

  def check_result(card)
    result = card.check_translation(trainer_params[:user_translation])

    if result[:state]
      if result[:distance].zero?
        flash[:notice] = t(:correct_translation_notice)
      else
        flash[:alert] = t 'translation_from_misprint_alert',
                          user_translation: trainer_params[:user_translation],
                          original_text: card.original_text,
                          translated_text: card.translated_text
      end
      redirect_to trainer_path
    else
      flash[:alert] = t(:incorrect_translation_alert)
      redirect_to trainer_path(id: card.id)
    end
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: 'Пользователь успешно удален.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/fillings/_form.html.erb
<%= simple_form_for filling do |f| %>
  <div class="form-group">
    <%= f.input :url,  as: :text, label: t(:enter_url_label),
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <div class="form-group">
    <%= f.input :original_selector,  as: :text, label: t(:original_selector_label),
                input_html: { class: 'form-control', required: true } %>
  </div>

  <div class="form-group">
    <%= f.input :translated_selector,  as: :text, label: t(:translated_selector_label),
                input_html: { class: 'form-control', required: true } %>
  </div>

  <div class="form-group">
    <%= f.input :block_id, collection: current_user.blocks.all.order('title'),
                      prompt: t(:choose_a_block), label: t(:blocks),
                      input_html: { class: 'form-control', required: true } %>
  </div>

  <%= f.button :submit, t(:save), class: 'btn btn-default' %>
<% end %>

app/views/dashboard/fillings/new.html.erb
<h2><%= t(:add_filling_label) %></h2>

<%= render 'form', filling: @filling %>

app/views/dashboard/fillings/show.html.erb
<p><%= t(:total_words_label) %>: <%= @cards.count %></p>
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th><%= t(:original_text_label) %></th>
    <th><%= t(:translated_text_label) %></th>
    <th><%= t(:revision) %></th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <% cache card do %>
        <tr class="table table-hover table-condensed">
          <td><%= card.original_text %></td>
          <td><%= card.translated_text %></td>
          <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
          <td><%= link_to t(:edit), edit_card_path(card) %></td>
          <td><%= link_to t(:delete), card, method: :delete,
                          data: { confirm: t(:delete_the_card) } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>